
mysql:
  url: '(127.0.0.1:3606)/go_web_base?charset=utf8&parseTime=True&loc=Local'
  username: 'root'
  password: 'root'
  max-idle-conns: 10
  min-open-conns: 10
  log-mode: false

redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 2
